--
-- V2: Create Items TABLE
--
--
-- CREATE TABLE Items (
--  id INT NOT NULL AUTO_INCREMENT,
--  name VARCHAR(50) NOT NULL,
--  quantity INT NOT NULL,
--  PRIMARY KEY (id),
--  UNIQUE INDEX (name)
-- ) DEFAULT CHARSET=utf8mb4;

-- 테이블 생성
CREATE TABLE TB_ALBUM (
  ALBUM_ID INT NOT NULL AUTO_INCREMENT,
  ALBUM_TITLE VARCHAR(500) NOT NULL,
  DELETE_YN CHAR(1) NOT NULL DEFAULT 'N',
  INSERTED_ID VARCHAR(100) NOT NULL,
  INSERTED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_ID VARCHAR(100),
  UPDATED_DATE DATETIME NOT NULL,
  PRIMARY KEY (ALBUM_ID),
  UNIQUE INDEX (ALBUM_TITLE)
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE TB_LOCALE (
  LOCALE_ID INT NOT NULL AUTO_INCREMENT,
  LOCALE_NAME VARCHAR(20) NOT NULL,
  DELETE_YN CHAR(1) NOT NULL DEFAULT 'N',
  INSERTED_ID VARCHAR(100) NOT NULL,
  INSERTED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_ID VARCHAR(100),
  UPDATED_DATE DATETIME NOT NULL,
  PRIMARY KEY (LOCALE_ID)
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE TB_ALBUM_LOCALE (
  ALBUM_ID INT NOT NULL,
  LOCALE_ID INT NOT NULL,
  DELETE_YN CHAR(1) NOT NULL DEFAULT 'N',
  INSERTED_ID VARCHAR(100) NOT NULL,
  INSERTED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_ID VARCHAR(100),
  UPDATED_DATE DATETIME NOT NULL,
  FOREIGN KEY(ALBUM_ID) REFERENCES TB_ALBUM(ALBUM_ID),
  FOREIGN KEY(LOCALE_ID) REFERENCES TB_LOCALE(LOCALE_ID)
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE TB_SONG (
  SONG_ID INT NOT NULL AUTO_INCREMENT,
  ALBUM_ID INT NOT NULL,
  SONG_TITLE VARCHAR(500) NOT NULL,
  SONG_LENGTH SMALLINT NOT NULL,
  TRACK_NO SMALLINT NOT NULL,
  DELETE_YN CHAR(1) NOT NULL DEFAULT 'N',
  INSERTED_ID VARCHAR(100) NOT NULL,
  INSERTED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_ID VARCHAR(100),
  UPDATED_DATE DATETIME NOT NULL,
  PRIMARY KEY (SONG_ID),
  UNIQUE INDEX (SONG_TITLE),
  FOREIGN KEY(ALBUM_ID) REFERENCES TB_ALBUM(ALBUM_ID)
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE TB_PLAYLIST (
  PLAYLIST_ID INT NOT NULL AUTO_INCREMENT,
  USER_ID INT NOT NULL,
  PLAYLIST_NAME VARCHAR(500) NOT NULL,
  DELETE_YN CHAR(1) NOT NULL DEFAULT 'N',
  INSERTED_ID VARCHAR(100) NOT NULL,
  INSERTED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_ID VARCHAR(100),
  UPDATED_DATE DATETIME NOT NULL,
  PRIMARY KEY (PLAYLIST_ID),
  UNIQUE INDEX (USER_ID)
) DEFAULT CHARSET = utf8mb4;

CREATE TABLE TB_PLAYLIST_SONG (
  PLAYLIST_ID INT NOT NULL ,
  SONG_ID INT NOT NULL,
  DELETE_YN CHAR(1) NOT NULL DEFAULT 'N',
  INSERTED_ID VARCHAR(100) NOT NULL,
  INSERTED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_ID VARCHAR(100),
  UPDATED_DATE DATETIME NOT NULL,
  FOREIGN KEY (PLAYLIST_ID) REFERENCES TB_PLAYLIST (PLAYLIST_ID),
  FOREIGN KEY (SONG_ID) REFERENCES TB_SONG (SONG_ID)
) DEFAULT CHARSET = utf8mb4;